services:
  pullsightai-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pullsightai-backend
    ports:
      - "3333:3333"
    restart: unless-stopped
    container_name: pullsightai-backend
    volumes:
      - /app/node_modules
    env_file:
      - ./backend/.env.docker
    networks:
      - pullsightai-network

  pullsightai-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: pullsightai-frontend
    volumes:
      - /app/node_modules
    depends_on:
      - pullsightai-backend
    env_file:
      - ./frontend/.env.docker
    networks:
      - pullsightai-network

  pullsightai-ai-agent:
    build:
      context: ./ai_agent
      dockerfile: Dockerfile
    image: pullsightai-ai-agent
    ports:
      - "8030:8030"
    restart: unless-stopped
    container_name: pullsightai-ai-agent
    env_file:
      - ./ai_agent/.env.docker
    depends_on:
      - pullsightai-backend
    networks:
      - pullsightai-network

networks:
  pullsightai-network:
    driver: bridge
