//////// SUCCESS RESPONSE ////////
export const SUCCESS = 'Success'
export const DATA_RETRIEVED = 'Data retrieved successfully'
export const PARTIAL_DATA_RETRIEVED = 'Partial data retrieved successfully'
export const CREATED = 'Created successfully'
export const BOOKING_COMPLETED = 'Booking completed successfully'
export const UPDATED = 'Updated successfully'
export const DELETED = 'Deleted successfully'
export const LOGOUT = 'Logged out successfully'
export const LOGGED_IN = 'Logged in successfully'
export const REGISTERED = 'Registered successfully'
export const RESET_PASSWORD = 'Password reset successfully'
export const PASSWORD_CHANGED = 'Password changed successfully'
export const EMAIL_SENT = 'Email sent successfully'
export const VALIDATED = 'Validated successfully'
export const UPLOADED = 'Uploaded successfully'
export const OTP_SENT = 'OTP sent successfully'
export const OTP_VERIFIED = 'OTP verified successfully'
export const SUBMITTED = 'Submitted successfully'
export const PAYMENT_INITIATED = 'Payment initiated successfully'
export const CERTIFICATE_ISSUED = 'Certificate issued successfully'

//////// FAILED RESPONSE
export const ERROR = 'Something went wrong'
